codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down

  status:
    project:
      default:
        enabled: yes
        target: auto
        base: auto
        threshold: 0.0

